### PR TITLE
Add new styles

### PR DESCRIPTION
**Pull request by ddamato**
- Separates illustrations from content.
- Corrected the LinkedIn icon.
- Small style updates for rounding, glass, font inheritance.

### CODE REVIEW

**Comment by stanchanpsu** [comment]
Hi @ddamato  :)

I love the glass!!

A few requests if possible:

- can the linkedin icon have just a bit more space (maybe 1 icon height) from the `content`
- on desktop, the `content` is a bit squished width-wise resulting in a few more lines of text than needed. Can it be stretched back out on larger screens?
image

Your thoughts: can the glass afford to be even more translucent?

**Comment by ddamato** [comment]
No problem, all done. I added a CSS variable to control the opacity so you can tweak easier.

**Review by stanchanpsu — APPROVED** [review]
Thanks so much. I'm gonna merge for us.

**Comment by stanchanpsu** [comment]
Deployed :) https://whencanipicklenyc.tiiny.site/

**Pull request merged**
